#!/bin/bash

# Copyright (C) Metaswitch Networks 2017
# If license terms are provided to you in a COPYING file in the root directory
# of the source code repository by which you are accessing this code, then
# the license outlined in that COPYING file applies to your use.
# Otherwise no rights are granted except for those provided to you by
# Metaswitch Networks in a separate written agreement.

local_site_name=site1
etcd_key=clearwater
. /etc/clearwater/config

# Check we can contact `etcd`
if ! nc -z ${management_local_ip:-$local_ip} 4000
then
  echo "The Clearwater Configuration store (etcd) is not running"
  echo "Please start it before displaying configuration"
  exit 2
fi

# Display the fallback ifcs configuration in etcd
clearwater-etcdctl get /$etcd_key/$local_site_name/configuration/fallback_ifcs
